import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import CustomCarousel from "./components/Carousel";
import React, { useEffect, useLayoutEffect, useRef } from "react";
import { Parallax, useParallax } from "react-scroll-parallax";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";
import mountainComponent from "./components/mountain";
import MountainComponent from "./components/mountain";

gsap.registerPlugin(ScrollTrigger, ScrollToPlugin); // Register the plugins

const Home: NextPage = () => {

  type DestinationKey = 'Adventure' | 'Sports' | 'New';


  const [exploreSelected, setExploreSelected] = React.useState<DestinationKey>('Adventure');
  // const parallax = useParallax<HTMLDivElement>({
  //   easing: 'easeOutCirc',
  //   speed: 2,
  //   translateY: [40, 0],
  // });

  // const textHeading = useParallax<HTMLDivElement>({
  //   easing: 'easeOutCirc',
  //   scale: [2, 1],
  //   translateY: [2, 0],
  //   opacity: [0, 1],
  // });

  const imageFirst = useParallax<HTMLDivElement>({
    easing: "ease",
    speed: 2,
    translateY: [50, 0],
  });

  const culture = useParallax<HTMLDivElement>({
    easing: "easeOutCirc",
    speed: 2,
    translateY: [30, 0],
  });

  const imageMain = useParallax<HTMLDivElement>({
    easing: "easeOutCirc",
    speed: 2,
    translateY: [50, -10],
  });
  const imageSecond = useParallax<HTMLDivElement>({
    easing: "easeOutCirc",
    speed: 20,
    translateY: [40, 0],
  });
  useEffect(() => {
    gsap.set(".top_banner", {
      background: "#fff",
      width: "100%",
      maxWidth: "100%",
      height: "100%",
      top: 0,
      minHeight: "100vh",
      // left: "50%",
      // x: "-50%",
    });
    gsap.set(".scrollDist", {
      width: "100%",
      height: "200%",
      position: "absolute",
    });
    gsap
      .timeline({
        scrollTrigger: {
          trigger: ".scrollDist",
          start: "top top",
          end: "bottom bottom",
          scrub: 1,
        },
      })
      .fromTo(".sky", { y: 0 }, { y: -200 }, 0)
      .fromTo(".cloud1", { y: 100 }, { y: -800 }, 0)
      .fromTo(".cloud2", { y: -150 }, { y: -500 }, 0)
      .fromTo(".cloud3", { y: -50 }, { y: -650 }, 0)
      .fromTo(".mountBg", { y: -10 }, { y: -100 }, 0)
      .fromTo(".mountMg", { y: -30 }, { y: -250 }, 0)
      .fromTo(".mountFg", { y: -50 }, { y: -600 }, 0);
  });

  const images = ["/lakhe.png", "/deuda.png", "/mask.png"];

  const destinations = {"Adventure":[

    {
      image: "/tilicho.jpg",
      title: "Kathmandu",
      description:
        "The capital city of Nepal, known for its rich history and culture.",
    },
    {
      image: "/temple.jpg",
      title: "Pokhara",
      description:
        "A beautiful city known for its stunning lakes and views of the Himalayas.",
    },
    {
      image: "/mountain.jpg",
      title: "Lumbini",
      description: "The birthplace of Buddha, a sacred place of pilgrimage.",
    } ],
    "Sports":[

      {
        image: "/tilicho.jpg",
        title: "Nepal",
        description:
          "The capital city of Nepal, known for its rich history and culture.",
      },
      {
        image: "/temple.jpg",
        title: "Pokhara",
        description:
          "A beautiful city known for its stunning lakes and views of the Himalayas.",
      },
      {
        image: "/mountain.jpg",
        title: "Lumbini",
        description: "The birthplace of Buddha, a sacred place of pilgrimage.",
      } ],
      "New":[

        {
          image: "/tilicho.jpg",
          title: "Kathmandu",
          description:
            "The capital city of Nepal, known for its rich history and culture.",
        },
        {
          image: "/temple.jpg",
          title: "Pokhara",
          description:
            "A beautiful city known for its stunning lakes and views of the Himalayas.",
        },
        {
          image: "/mountain.jpg",
          title: "Lumbini",
          description: "The birthplace of Buddha, a sacred place of pilgrimage.",
        } ]};

  return (
    <div className="d-block">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <div className="position-relative">
        <nav className="navbar navbar-expand-lg navbar-light position-absolute  w-100 ">
          <div className="container-fluid">
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>
            <div
              className="collapse navbar-collapse "
              id="navbarSupportedContent"
            >
              <ul
                className="navbar-nav ms-auto mt-2 gap-2 "
                style={{ marginRight: 100 }}
              >
                <li className="nav-item">
                  <a className="nav-link " aria-current="page" href="#">
                    Home
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    Why
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link " href="#">
                    Culture
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    Explore
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div className="scrollDist"></div>
        <div className={`top_banner`}>
          <svg viewBox="0 0 1200 800" xmlns="http://www.w3.org/2000/svg">
            <mask id="m">
              <g className="cloud1">
                <rect fill="#fff" width="100%" height="800" y="799" />
                <image
                  href="https://assets.codepen.io/721952/cloud1Mask.jpg"
                  width="1200"
                  height="800"
                />
              </g>
            </mask>

            <image
              className="sky"
              href="https://assets.codepen.io/721952/sky.jpg"
              width="1200"
              height="590"
            />
            <image
              className="mountBg"
              href="https://assets.codepen.io/721952/mountBg.png"
              width="1200"
              height="800"
            />
            <image
              className="mountMg"
              href="https://assets.codepen.io/721952/mountMg.png"
              width="1200"
              height="800"
            />
            <image
              className="cloud2"
              href="https://assets.codepen.io/721952/cloud2.png"
              width="1200"
              height="800"
            />
            <image
              className="mountFg"
              href="https://assets.codepen.io/721952/mountFg.png"
              width="1200"
              height="800"
            />
            <image
              className="cloud1"
              href="https://assets.codepen.io/721952/cloud1.png"
              width="1200"
              height="800"
            />
            <image
              className="cloud3"
              href="https://assets.codepen.io/721952/cloud3.png"
              width="1200"
              height="800"
            />
            <text
              fontSize={85}
              fontFamily="Montserrat"
              fill="#fff"
              alignmentBaseline="middle"
              textAnchor="middle"
              x="50%"
              y="200"
            >
              NATURALLY
            </text>
            <polyline
              className="arrow"
              fill="#fff"
              points="599,250 599,289 590,279 590,282 600,292 610,282 610,279 601,289 601,250"
            />

            <g mask="url(#m)">
              <rect fill="#fff" width="1200" height="100%" />
              <text
                fontSize={99}
                fontFamily="Montserrat"
                alignmentBaseline="middle"
                textAnchor="middle"
                x="50%"
                y="500"
                fill="#162a43"
              >
                NEPAL
              </text>

              <text
                fontSize={28}
                fontFamily=""
                alignmentBaseline="middle"
                textAnchor="middle"
                x="50%"
                y="580"
                fill="#162a43"
              >
                Once is not enough.
              </text>
            </g>

            <rect
              id="arrowBtn"
              width="100"
              height="100"
              opacity="0"
              x="550"
              y="220"
              style={{ cursor: "pointer" }}
            />
          </svg>
        </div>
      </div>

      {/* <div className="container">
        <div className="row">
          <div className="col-12">
            <div className="row">
              <div className="col-12">
                <h1>WELCOME TO</h1>
              </div>
              <div className="col-12">
                <h2>THE JUNGLE</h2>
              </div>
            </div>
          </div>
        </div>
      </div> */}

      <div className={`${styles.block_why_nepal} container-fluid section`}>
        {/* <p style={{ fontSize: 28 }}>
          WHAT MAKE NEPAL THE BEST COUNTRY TO TRAVEL
        </p> */}
        <h2 className={styles.section_heading}>Why Nepal</h2>
        <div className="row mt-5 w-80">
          <div className="col pt-4 mt-5" ref={culture.ref}>
            <ul className={styles.block_why_nepal_list}>
              <li className={styles.block_why_nepal_item}>
                <div className="d-flex flex-column align-items-center text-center">
                  <div className="p-4">
                    <MountainComponent></MountainComponent>
                  </div>
                  <h3>Himalayan Wonders</h3>
                  <p>
                    Discover Nepal's awe-inspiring landscapes, from the world's
                    highest peaks to lush valleys. With iconic trekking trails
                    like Everest Base Camp, Nepal offers an unparalleled
                    adventure in nature.{" "}
                  </p>
                </div>
              </li>
              <li className={`${styles.block_why_nepal_item} `}>
                <div className="d-flex flex-column align-items-center text-center">
                  <div className="p-4 ">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      strokeWidth={"3px"}
                      viewBox="0 0 512 512"
                      width={44}
                      height={44}
                    >
                      <path d="M508.405 234.268a10.206 10.206 0 0 0-8.252-2.293l-5.509.903a931.152 931.152 0 0 0-91.383 19.724C400.5 173.755 335.509 110.458 256 110.458c-79.511 0-144.505 63.3-147.26 142.151a930.33 930.33 0 0 0-91.383-19.731l-5.509-.903A10.198 10.198 0 0 0 0 242.04v242.755a10.2 10.2 0 0 0 10.199 10.21h491.602c5.632 0 10.199-4.566 10.199-10.199V242.04a10.2 10.2 0 0 0-3.595-7.772zM256 130.857c70.007 0 126.964 56.955 126.964 126.964 0 .164-.005.331-.006.496a929.83 929.83 0 0 0-126.961 47.565 930.622 930.622 0 0 0-126.957-47.559c0-.165-.004-.336-.004-.502 0-70.009 56.957-126.964 126.964-126.964zM20.398 254.069a910.184 910.184 0 0 1 211.475 63.342A929.719 929.719 0 0 0 20.398 461.469v-207.4zm471.204 220.539H36.272C164.445 359.225 321.382 283.17 491.601 254.07v220.538zM253.573 16.994c-5.632 0-10.199 4.566-10.199 10.199v42.484c0 5.633 4.567 10.199 10.199 10.199s10.199-4.566 10.199-10.199V27.193c0-5.633-4.567-10.199-10.199-10.199zM154.785 100.827l-24.972-34.37c-3.312-4.558-9.69-5.567-14.246-2.256-4.557 3.311-5.567 9.689-2.256 14.246l24.972 34.37a10.185 10.185 0 0 0 8.259 4.205c2.079 0 4.178-.633 5.987-1.949 4.557-3.31 5.567-9.689 2.256-14.246z" />
                      <path d="M84.923 190.089 44.519 176.96c-5.356-1.739-11.111 1.19-12.852 6.548-1.74 5.359 1.191 11.113 6.549 12.853L78.62 209.49c1.046.34 2.108.502 3.154.502 4.299 0 8.298-2.741 9.698-7.051 1.74-5.358-1.192-11.111-6.549-12.852zM480.511 176.583c-1.74-5.357-7.494-8.29-12.852-6.548l-40.404 13.128c-5.358 1.741-8.289 7.495-6.549 12.852 1.4 4.31 5.398 7.05 9.698 7.05a10.21 10.21 0 0 0 3.154-.502l40.404-13.128c5.358-1.741 8.289-7.495 6.549-12.852zM392.968 59.919c-4.558-3.311-10.937-2.301-14.246 2.256l-24.971 34.37c-3.312 4.558-2.301 10.936 2.256 14.247a10.145 10.145 0 0 0 5.987 1.948c3.154 0 6.264-1.458 8.259-4.205l24.971-34.37c3.312-4.556 2.301-10.935-2.256-14.246zM314.135 439.586h-11.219c-5.632 0-10.199 4.566-10.199 10.199s4.567 10.199 10.199 10.199h11.219c5.632 0 10.199-4.566 10.199-10.199.001-5.633-4.567-10.199-10.199-10.199zM466.784 439.586H354.932c-5.632 0-10.199 4.566-10.199 10.199s4.567 10.199 10.199 10.199h111.852c5.632 0 10.199-4.566 10.199-10.199s-4.567-10.199-10.199-10.199z" />
                    </svg>
                  </div>
                  <h3>Cultural Treasures</h3>
                  <p>
                    Uncover Nepal's rich heritage through ancient temples,
                    UNESCO sites, and warm encounters with local traditions.
                  </p>
                </div>
              </li>
              <li className={styles.block_why_nepal_item}>
                <div className="d-flex flex-column align-items-center text-center">
                  <div className="p-4">
                    <MountainComponent></MountainComponent>
                  </div>
                  <h3>Serene Spirituality</h3>
                  <p>
                  Find tranquility in Nepal's spiritual hubs, from the birthplace of Buddha to the peaceful Himalayan landscapes.
                  </p>
                </div>
              </li>
            </ul>
          </div>

          <div className="col px-5">
            <div className="position-relative d-block w-100 h-100">
              <div ref={imageMain.ref} className={styles.why_name_image_second}>
                <img src={"/temple.jpg"} style={{ width: "100%" }}></img>
              </div>
              <div className={styles.why_name_image_first}>
                <div ref={imageFirst.ref}>
                  {/* <div style={{position:"absolute",top:'0px',left:'0',width:"100%",height:"100%",objectFit:"cover"}}> */}

                  <div style={{ position: "relative" }} ref={imageSecond.ref}>
                    <img src={"/mane.jpg"} style={{ width: "100%" }}></img>
                    {/* </div> */}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="col mt-5 pt-4">
            <div className="d-flex flex-column ">
              <h3>Best country to travel</h3>
              <p>
                Beautiful Nepal is a land of friendly and engaging people, where
                deities mingle with mortals and magnificent temples, monasteries
                and historical monuments can be found at almost every turn. This
                is the home of Sagarmatha “Goddess Mother of the World”, the
                iconic Mount Everest, and her snow-capped counterparts making up
                the weather-beaten Himalayas.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className={`${styles.block_culture} section container-fluid `}>
        <div
          className={`${styles.block_culture_content} container-fluid p-0 m-0`}
        >
          <div className="row justify-content-center h-100 align-items-center ">
            <div className="col-5 mx-auto">
              <div id="cf4a">
                {images.map((src, index) => (
                  <img
                    key={index}
                    src={src}
                    className="mx-auto d-block fade"
                    width={300}
                  />
                ))}
              </div>
            </div>
            <div className="col-7 center  p-5  h-100  m-0 justify-content-center d-flex flex-column">
              <div className={`${styles.section_heading} `}>
                {" "}
                Experience the Culture
              </div>
              <div className="mt-2">
                <h1 className={styles.sub_section_heading}>LIVING HERITAGE</h1>
                <p className={styles.section_text}>
                In this land of diverse ethnic groups, traditions weave through the tapestry of everyday life. From the vibrant festivals like Dashain and Tihar to the ancient temples and palaces of Kathmandu Durbar Square, Nepal's cultural richness unfolds in every corner. Explore the living heritage sites, witness traditional arts and crafts, and engage with warm-hearted locals eager to share their stories. As you journey through this enchanting landscape, you'll discover that Nepal's true beauty lies not only in its majestic mountains but also in the vibrant, welcoming communities that make it a unique and unforgettable experience.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className={`${styles["block-explore"]} `}>
        <div className="d-flex flex-row">
          <div className={`${styles["block-explore__first"]} col-12 col-md-6`}>
            <h3>{ destinations.Adventure[0].title}</h3>
            <p>{destinations.Adventure[0].description}</p>
            <button type="button" className="btn btn-primary">
              See More
            </button>

            <div
              className={`${styles["block-explore__first__carousel_indicator"]} carousel-indicators`}
            >
              <button
                type="button"
                data-bs-target="#carouselExampleIndicators"
                data-bs-slide-to="0"
                className="active"
                aria-current="true"
                aria-label="Slide 1"
              ></button>
              <button
                type="button"
                data-bs-target="#carouselExampleIndicators"
                data-bs-slide-to="1"
                aria-label="Slide 2"
              ></button>
              <button
                type="button"
                data-bs-target="#carouselExampleIndicators"
                data-bs-slide-to="2"
                aria-label="Slide 3"
              ></button>
            </div>

            {/* <img
              src="/temple.jpg"
              width="100%"
              height={400}
              style={{ objectFit: "cover" }}
            /> */}
          </div>

          <div
            className={`${styles["block-explore__second"]} col-12 col-md-6 d-flex flex-column justify-content-center `}
          >
            <div className={styles["block-explore__second__wrapper"]}>
              <h2>Explore</h2>
              <ul className={styles["block-explore__second__unordered-list"]}>


                {Object.keys(destinations).map((key, index) => (

                  <li key={index} 
                  className={
                    `${styles["block-explore__second__unordered-list__list_item"]} ${exploreSelected == key?styles["block-explore__second__unordered-list__list_item__selected"]:""}`
                  }
                >
                  <a onClick={a=>setExploreSelected(key as DestinationKey)}>{key}</a>
                </li>

                ))}
              
                
              </ul>
              <div className=" flex row gx-3">
             
                {destinations[exploreSelected].map((destination, index) => (
                  <div key={index} className="col-sm-12 col-md-6 col-lg-4">
                    <div
                      className={`${
                        styles["block-explore__second__item-wrapper"]
                      }   ${
                        index == 1
                          ? styles[
                              "block-explore__second__item-wrapper__selected"
                            ]
                          : ""
                      }`}
                      style={{
                        backgroundImage: `linear-gradient( rgba(0,0,0,0), rgba(0,0,0,0), rgba(0,0,0,.8) ), url(${destination.image})`,
                      }}
                    >
                      <div
                        className={`${styles["block-explore__second__list-wrapper__content"]} `}
                      >
                        <h4>{destination.title}</h4>
                        <p>{destination.description}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div style={{ height: 100 }}></div>
    </div>
  );
};

export default Home;
